import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';
import type { DataStore, ProjectConfig, ChannelBinding, ThreadSession, WorktreeMapping, PassthroughThread, QueuedMessage, QueueSettings, UserPersonality, MemoryEntry } from '../types/index.js';
import { sanitizeModel } from '../utils/stringUtils.js';
const CONFIG_DIR = join(homedir(), '.remote-opencode'); const DATA_FILE = join(CONFIG_DIR, 'data.json');
function ensureDataDir(){if(!existsSync(CONFIG_DIR))mkdirSync(CONFIG_DIR,{recursive:true});}
function loadData():DataStore{ensureDataDir();if(!existsSync(DATA_FILE))return{projects:[],bindings:[]};try{return JSON.parse(readFileSync(DATA_FILE,'utf-8')) as DataStore}catch{return{projects:[],bindings:[]}}}
function saveData(data:DataStore){ensureDataDir();writeFileSync(DATA_FILE,JSON.stringify(data,null,2),'utf-8');}
export function setUserPersonality(userId:string,personality:string){const d=loadData();if(!d.userPersonalities)d.userPersonalities=[];const i=d.userPersonalities.findIndex(p=>p.userId===userId);const v:UserPersonality={userId,personality,updatedAt:Date.now()};if(i>=0)d.userPersonalities[i]=v;else d.userPersonalities.push(v);saveData(d)}
export function getUserPersonality(userId:string){return loadData().userPersonalities?.find(p=>p.userId===userId)?.personality}
export function removeUserPersonality(userId:string){const d=loadData();if(!d.userPersonalities)return false;const i=d.userPersonalities.findIndex(p=>p.userId===userId);if(i<0)return false;d.userPersonalities.splice(i,1);saveData(d);return true}
export function addProject(alias:string,path:string){const d=loadData();const i=d.projects.findIndex(p=>p.alias===alias);if(i>=0)d.projects[i].path=path;else d.projects.push({alias,path});saveData(d)}
export function getProjects(){return loadData().projects} export function getProject(alias:string){return loadData().projects.find(p=>p.alias===alias)}
export function removeProject(alias:string){const d=loadData();const i=d.projects.findIndex(p=>p.alias===alias);if(i<0)return false;d.projects.splice(i,1);d.bindings=d.bindings.filter(b=>b.projectAlias!==alias);saveData(d);return true}
export function setChannelBinding(channelId:string,projectAlias:string,model?:string){const d=loadData();const i=d.bindings.findIndex(b=>b.channelId===channelId);if(i>=0){d.bindings[i].projectAlias=projectAlias;if(model!==undefined)d.bindings[i].model=model}else d.bindings.push({channelId,projectAlias,model});saveData(d)}
export function setChannelModel(channelId:string,model:string){const d=loadData();const clean=sanitizeModel(model);const i=d.bindings.findIndex(b=>b.channelId===channelId);if(i>=0)d.bindings[i].model=clean;else{if(!d.channelModels)d.channelModels={};d.channelModels[channelId]=clean}saveData(d);return true}
export function getChannelModel(channelId:string){const d=loadData();return sanitizeModel(d.bindings.find(b=>b.channelId===channelId)?.model??d.channelModels?.[channelId]??'')}
export function getChannelBinding(channelId:string){return loadData().bindings.find(b=>b.channelId===channelId)?.projectAlias} export function getChannelProjectPath(channelId:string){const a=getChannelBinding(channelId);return a?getProject(a)?.path:undefined}
export function getThreadSession(threadId:string){return loadData().threadSessions?.find(s=>s.threadId===threadId)} export function setThreadSession(session:ThreadSession){const d=loadData();if(!d.threadSessions)d.threadSessions=[];const i=d.threadSessions.findIndex(s=>s.threadId===session.threadId);if(i>=0)d.threadSessions[i]=session;else d.threadSessions.push(session);saveData(d)}
export function updateThreadSessionLastUsed(threadId:string){const d=loadData();const s=d.threadSessions?.find(s=>s.threadId===threadId);if(s){s.lastUsedAt=Date.now();saveData(d)}} export function clearThreadSession(threadId:string){const d=loadData();if(d.threadSessions){d.threadSessions=d.threadSessions.filter(s=>s.threadId!==threadId);saveData(d)}} export function getAllThreadSessions(){return loadData().threadSessions??[]}
export function setWorktreeMapping(m:WorktreeMapping){const d=loadData();if(!d.worktreeMappings)d.worktreeMappings=[];const i=d.worktreeMappings.findIndex(x=>x.threadId===m.threadId);if(i>=0)d.worktreeMappings[i]=m;else d.worktreeMappings.push(m);saveData(d)} export function getWorktreeMapping(id:string){return loadData().worktreeMappings?.find(m=>m.threadId===id)} export function getWorktreeMappingByBranch(p:string,b:string){return loadData().worktreeMappings?.find(m=>m.projectPath===p&&m.branchName===b)} export function removeWorktreeMapping(id:string){const d=loadData();if(!d.worktreeMappings)return false;const i=d.worktreeMappings.findIndex(m=>m.threadId===id);if(i<0)return false;d.worktreeMappings.splice(i,1);saveData(d);return true} export function getAllWorktreeMappings(){return loadData().worktreeMappings??[]} export function getWorktreeMappingsByProject(p:string){return loadData().worktreeMappings?.filter(m=>m.projectPath===p)??[]}
export function setPassthroughMode(id:string,enabled:boolean,userId:string){const d=loadData();if(!d.passthroughThreads)d.passthroughThreads=[];const v={threadId:id,enabled,enabledBy:userId,enabledAt:Date.now()};const i=d.passthroughThreads.findIndex(p=>p.threadId===id);if(i>=0)d.passthroughThreads[i]=v;else d.passthroughThreads.push(v);saveData(d)} export function getPassthroughMode(id:string){return loadData().passthroughThreads?.find(p=>p.threadId===id)} export function isPassthroughEnabled(id:string){return getPassthroughMode(id)?.enabled??false} export function removePassthroughMode(id:string){const d=loadData();if(!d.passthroughThreads)return false;const i=d.passthroughThreads.findIndex(p=>p.threadId===id);if(i<0)return false;d.passthroughThreads.splice(i,1);saveData(d);return true}
export function setProjectAutoWorktree(a:string,e:boolean){const d=loadData();const p=d.projects.find(p=>p.alias===a);if(!p)return false;p.autoWorktree=e;saveData(d);return true} export function getProjectAutoWorktree(a:string){return getProject(a)?.autoWorktree??false} export function setProjectAutoPassthrough(a:string,e:boolean){const d=loadData();const p=d.projects.find(p=>p.alias===a);if(!p)return false;p.autoPassthrough=e;saveData(d);return true} export function getProjectAutoPassthrough(a:string){return getProject(a)?.autoPassthrough??false}
export function getQueue(id:string){return loadData().queues?.[id]??[]} export function addToQueue(id:string,m:QueuedMessage){const d=loadData();if(!d.queues)d.queues={};if(!d.queues[id])d.queues[id]=[];d.queues[id].push(m);saveData(d)} export function popFromQueue(id:string){const d=loadData();if(!d.queues?.[id]?.length)return undefined;const m=d.queues[id].shift();saveData(d);return m} export function clearQueue(id:string){const d=loadData();if(d.queues?.[id]){delete d.queues[id];saveData(d)}} export function getQueueSettings(id:string){return loadData().queueSettings?.[id]??{paused:false,continueOnFailure:false,freshContext:false}} export function updateQueueSettings(id:string,s:Partial<QueueSettings>){const d=loadData();if(!d.queueSettings)d.queueSettings={};d.queueSettings[id]={...getQueueSettings(id),...s};saveData(d)}
export function getMemories():MemoryEntry[]{return loadData().memories??[]} export function setMemories(memories:MemoryEntry[]){const d=loadData();d.memories=memories;saveData(d)}
