import { TextBasedChannel, EmbedBuilder, Message, ChatInputCommandInteraction } from 'discord.js';
import * as dataStore from './dataStore.js';
import * as sessionManager from './sessionManager.js';
import * as serveManager from './serveManager.js';
import * as worktreeManager from './worktreeManager.js';
import * as storage from './storageService.js';
import * as guildPersonality from './guildPersonalityStore.js';
import * as memory from './memoryService.js';
import { SSEClient } from './sseClient.js';
import { formatOutputForMobile } from '../utils/messageFormatter.js';

async function reactToLatestUserMessage(channel: TextBasedChannel, emoji: string): Promise<void> { try { if (!("messages" in channel)) return; const messages = await (channel as any).messages.fetch({ limit: 20 }); const target = messages.find((message: Message) => !message.author.bot && !message.system); if (target) await target.react(emoji); } catch (error) { console.error(`Failed to add AI reaction ${emoji}:`, error instanceof Error ? error.message : error); } }
async function processAiReactions(channel: TextBasedChannel, text: string): Promise<string> { const reactions: string[]=[]; const cleaned=text.replace(/\[react:([^\]\r\n]{1,64})\]/gu,(_m,emojiText:string)=>{const segmenter=new Intl.Segmenter(undefined,{granularity:'grapheme'});for(const part of segmenter.segment(emojiText.trim())){const emoji=part.segment.trim();if(emoji)reactions.push(emoji)}return ''});for(const emoji of reactions)await reactToLatestUserMessage(channel,emoji);return cleaned.replace(/[ \t]{2,}/g,' ').replace(/\n{3,}/g,'\n\n').trim();}
export interface RunPromptMedia { url:string; name:string; mime?:string|null; }
export async function runPrompt(channel:TextBasedChannel|null,threadId:string,prompt:string,parentChannelId:string,userId?:string,interaction?:ChatInputCommandInteraction,media:RunPromptMedia[]=[]):Promise<void>{
 const storageEnabled=storage.isEnabled(threadId);const projectPath=storage.getWorkspace(threadId);const configuredProjectPath=dataStore.getChannelProjectPath(parentChannelId);let worktreeMapping=storageEnabled?dataStore.getWorktreeMapping(threadId):undefined;
 if(storageEnabled&&!worktreeMapping){const projectAlias=dataStore.getChannelBinding(parentChannelId);if(projectAlias&&dataStore.getProjectAutoWorktree(projectAlias)&&configuredProjectPath){try{const branchName=worktreeManager.sanitizeBranchName(`auto/${threadId.slice(0,8)}-${Date.now()}`);const worktreePath=await worktreeManager.createWorktree(configuredProjectPath,branchName);const newMapping={threadId,branchName,worktreePath,projectPath:configuredProjectPath,description:prompt.slice(0,50)+(prompt.length>50?'...':''),createdAt:Date.now()};dataStore.setWorktreeMapping(newMapping);worktreeMapping=newMapping;if(channel){const embed=new EmbedBuilder().setTitle(`🌳 Auto-Worktree: ${branchName}`).setDescription('Automatically created for this session').addFields({name:'Branch',value:branchName,inline:true},{name:'Path',value:worktreePath,inline:true}).setColor(0x2ecc71);await(channel as any).send({embeds:[embed]});}}catch(error){console.error('Auto-worktree creation failed:',error)}}}
 const effectivePath=storageEnabled?(worktreeMapping?.worktreePath??projectPath):projectPath;const preferredModel=dataStore.getChannelModel(parentChannelId);try{if(channel)await(channel as any).sendTyping()}catch{}
 let port:number;let sessionId:string;let accumulatedText='';let promptSent=false;let hasSessionError=false;let responseHandled=false;let runningIndicator:Message|null=null;let runningIndicatorInterval:NodeJS.Timeout|null=null;let sseClient:SSEClient|null=null;
 const startRunningIndicator=async()=>{if(!channel)return;try{runningIndicator=await(channel as any).send('⠋');const spinner=['⠋','⠙','⠹','⠸','⠼','⠴','⠦','⠧','⠇','⠏'];let tick=0;runningIndicatorInterval=setInterval(()=>{if(runningIndicator)runningIndicator.edit({content:spinner[tick++%spinner.length]}).catch(()=>{})},700)}catch(error){console.error('Failed to start running indicator:',error)}};
 const stopRunningIndicator=async()=>{if(runningIndicatorInterval){clearInterval(runningIndicatorInterval);runningIndicatorInterval=null}if(runningIndicator){const indicator=runningIndicator;runningIndicator=null;await indicator.delete().catch(()=>{})}};
 const sendOutput=async(content:string):Promise<boolean>=>{try{await stopRunningIndicator();if(interaction){if(!interaction.replied&&!interaction.deferred)await interaction.reply({content});else await interaction.followUp({content});return true}if(!channel)return false;await(channel as any).send({content});return true}catch(error){console.error('Failed to send AI response:',error);return false}};
 const cleanup=async()=>{if(sseClient){sseClient.disconnect();sseClient=null}sessionManager.clearSseClient(threadId);await stopRunningIndicator()};
 try{
  await new Promise<void>(r=>setTimeout(r,2000));await startRunningIndicator();port=await serveManager.spawnServe(effectivePath,preferredModel,storageEnabled);await serveManager.waitForReady(port,30000,effectivePath,preferredModel,storageEnabled);const settings=dataStore.getQueueSettings(threadId);if(settings.freshContext)sessionManager.clearSessionForThread(threadId);sessionId=await sessionManager.ensureSessionForThread(threadId,effectivePath,port);
  sseClient=new SSEClient();const sseReady=new Promise<void>((resolve,reject)=>{let settled=false;const timeout=setTimeout(()=>{if(!settled){settled=true;reject(new Error('Timed out waiting for OpenCode SSE connection'))}},10000);sseClient!.onConnected(()=>{if(!settled){settled=true;clearTimeout(timeout);resolve()}});sseClient!.onError(error=>{if(!settled){settled=true;clearTimeout(timeout);reject(error)}})});sessionManager.setSseClient(threadId,sseClient);
  sseClient.onPartUpdated(part=>{if(part.sessionID===sessionId)accumulatedText=part.text});
  sseClient.onSessionIdle(idleSessionId=>{if(idleSessionId!==sessionId||!promptSent||responseHandled)return;responseHandled=true;(async()=>{try{if(hasSessionError){await cleanup();return}if(!accumulatedText.trim())await sendOutput('⚠️ No output received — the model may have encountered an issue.');else{const reactedText=channel?await processAiReactions(channel,accumulatedText):accumulatedText.replace(/\[react:([^\]\r\n]{1,64})\]/gu,'').trim();if(reactedText){const result=formatOutputForMobile(reactedText);for(const chunk of result.chunks)await sendOutput(chunk)}else await stopRunningIndicator();memory.remember(threadId,userId??'unknown','assistant',reactedText)}await cleanup()}catch(error){await cleanup();console.error('Error in onSessionIdle:',error)}})()});
  sseClient.onSessionError((errorSessionId,errorInfo)=>{if(errorSessionId!==sessionId||!promptSent||responseHandled)return;hasSessionError=true;responseHandled=true;console.error('OpenCode session error:',errorInfo);cleanup().catch(console.error)});sseClient.connect(`http://127.0.0.1:${port}`);await sseReady;
  const guildId=channel&&'guildId'in channel?((channel as any).guildId as string|null):null;const serverPersonality=guildId?guildPersonality.getPersonality(guildId):undefined;const personality=serverPersonality??(userId?dataStore.getUserPersonality(userId):undefined);
  const reactionInstructions='\n\nDiscord reaction capability: You may react to the user\'s latest message when genuinely appropriate using [react:EMOJI]. Reactions are occasional, never constant.';
  const mediaInstructions=media.length?`\n\n[Discord media attached]\nThe attached image/GIF files are actual user-provided media. Inspect them when your selected model supports image input.\n${media.map(item=>`- ${item.name}`).join('\n')}`:'';
  const outputContract=`\n\n[STRICT OUTPUT CONTRACT]\nYour response is sent directly to Discord. Output ONLY the actual message Leeha should send right now. Do not expose or narrate internal reasoning, planning, deliberation, chain-of-thought, conversation-management decisions, or tool/session state. Never output headings or phrases such as "Status:", "Next step:", "Suggested next action:", "what I'd do next", "the cleanest move", "the open thread", "lead I haven't fully closed", "unless you (creator)", or similar internal planning language. Never call the user "creator" unless the current Discord message explicitly does so. Do not summarize who said what merely to explain your decision. Do not describe whether you should reply, wait, ignore someone, or chase a conversation; silently make that decision. If there is no natural message for Leeha to send, produce an empty response rather than explaining why. Keep multi-user identities separate and address only the person/message that is actually relevant.\n`;
  const longTermMemory=memory.buildMemoryContext(threadId,userId??'unknown',prompt);
  const effectivePrompt=(personality?`[Permanent personality instructions]\n${personality}\n\n`:'')+outputContract+`${longTermMemory}\n\n[Current user message]\n${prompt}${mediaInstructions}${reactionInstructions}`;
  memory.remember(threadId,userId??'unknown','user',prompt);promptSent=true;await sessionManager.sendPrompt(port,sessionId,effectivePrompt,preferredModel,media);
 }catch(error){await cleanup();console.error('OpenCode execution failed:',error)}
}
